name: cloudwalk_challenge
description: Cloudwalk's challenge to show a list of pictures of the day from NASA's API, "APOD".

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^5.0.3
  intl: ^0.18.0
  modular_bloc_bind: ^1.0.1
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  transparent_image: ^2.0.0

dev_dependencies:
  dart_code_metrics: ^5.7.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
