name: cloudwalk_challenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^5.0.3
  intl: ^0.17.0
  modular_bloc_bind: ^1.0.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  transparent_image: ^2.0.0

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
